# Generated by Django 4.2.22 on 2025-06-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('admission_date', models.DateField()),
                ('photo', models.ImageField(upload_to='children/')),
                ('background_info', models.TextField(blank=True)),
            ],
        ),
    ]
