# Generated by Django 4.2.22 on 2025-06-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_oldage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100)),
                ('donor_email', models.EmailField(max_length=254)),
                ('donor_phone', models.CharField(max_length=15)),
                ('donation_date', models.DateField()),
                ('occasion', models.CharField(blank=True, max_length=100)),
                ('meal_time', models.CharField(max_length=20)),
                ('combo', models.CharField(max_length=200)),
            ],
        ),
    ]
