# Generated by Django 4.2.22 on 2025-06-20 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_mealdonation_recipient'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mealdonation',
            unique_together={('donation_date', 'meal_time')},
        ),
    ]
