# Generated by Django 4.2.22 on 2025-06-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='phone',
            field=models.CharField(default='unknown', max_length=15),
            preserve_default=False,
        ),
    ]
