# Generated by Django 4.2.22 on 2025-06-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_sponsor_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldAgePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('photo', models.ImageField(upload_to='elders/')),
                ('description', models.TextField(blank=True)),
                ('suffering_from', models.CharField(help_text='Health issues or conditions', max_length=255)),
                ('medical_expenses', models.DecimalField(decimal_places=2, help_text='Monthly medicine expenses (INR)', max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Oldage',
        ),
    ]
