# Generated by Django 4.2.22 on 2025-06-20 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_oldageperson_delete_oldage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldAgeNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('quantity', models.CharField(blank=True, max_length=50)),
                ('note', models.TextField(blank=True)),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needs', to='myapp.oldageperson')),
            ],
        ),
    ]
