# Generated by Django 4.2.22 on 2025-06-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_oldageneed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldageneed',
            name='elder',
        ),
        migrations.AddField(
            model_name='oldageneed',
            name='elders',
            field=models.ManyToManyField(related_name='needs', to='myapp.oldageperson'),
        ),
    ]
