# Generated by Django 4.2.22 on 2025-06-20 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_oldageneed_elder_oldageneed_elders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldageneed',
            name='elders',
        ),
    ]
