# Generated by Django 4.2.22 on 2025-06-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_oldageneed_elders'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoClassRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('skills', models.TextField()),
                ('message', models.TextField()),
                ('preferred_date', models.DateField()),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
