# Generated by Django 4.2.22 on 2025-06-21 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_democlassregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='democlassregistration',
            name='preferred_date',
        ),
    ]
