# Generated by Django 4.2.22 on 2025-06-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_democlassregistration_preferred_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='democlassregistration',
            name='phone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
