# Generated by Django 4.2.22 on 2025-06-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_democlassregistration_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralChildNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('quantity_needed', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='democlassregistration',
            name='phone',
        ),
    ]
