# Generated by Django 4.2.22 on 2025-06-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_generalchildneed_remove_democlassregistration_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('items', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='donation_images/')),
                ('delivery', models.CharField(max_length=20)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
