# Generated by Django 4.2.22 on 2025-06-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_generaldonation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generaldonation',
            old_name='submitted_on',
            new_name='submitted_at',
        ),
        migrations.AlterField(
            model_name='generaldonation',
            name='delivery',
            field=models.CharField(choices=[('drop', 'Drop at Orphanage'), ('pickup', 'Pickup Required')], max_length=10),
        ),
    ]
