# Generated by Django 4.2.22 on 2025-06-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_gallerycategory_galleryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='category',
        ),
        migrations.RenameField(
            model_name='generaldonation',
            old_name='submitted_at',
            new_name='date',
        ),
        migrations.AddField(
            model_name='generaldonation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generaldonation',
            name='phone',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generaldonation',
            name='delivery',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='GalleryCategory',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
