# Generated by Django 4.2.22 on 2025-06-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_galleryimage_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generaldonation',
            old_name='date',
            new_name='submitted_at',
        ),
        migrations.AlterField(
            model_name='generaldonation',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generaldonation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='generaldonation',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
