# Generated by Django 4.2.22 on 2025-06-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(choices=[('infrastructure', 'Infrastructure'), ('children', 'Our Child Pictures'), ('oldage', 'Old Age Picks'), ('donations', 'Donations')], max_length=20)),
            ],
        ),
    ]
