# Generated by Django 4.2.22 on 2025-06-25 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('infrastructure', 'Infrastructure'), ('children', 'Our Child Pictures'), ('oldage', 'Old Age Picks'), ('donations', 'Donations')], max_length=50),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery_images/'),
        ),
    ]
