# Generated by Django 4.2.22 on 2025-08-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_galleryimage_uploaded_at_alter_galleryimage_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MealDonationRecipient',
        ),
        migrations.AddField(
            model_name='mealdonation',
            name='recipient',
            field=models.TextField(blank=True),
        ),
    ]
